### ISSUE TITLE
Use a "simpler" cache frontend for message passing

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/jobqueue-common#28]
In #27 we realized that #26 added explicit use of `serialize()` and `unserialize()` on the messages stored in the cache, even though the used `VariableFrontend` does exactly that on it's own.

Thus two options are left:

- remove the manual serialization and keep the `VariableFrontend`
- switch to the `StringFrontend`

The first breaks messages still in the cache when the coe is updated, the latter is B/C but keeps the code "dirty".

**Comment by kitsunet** [comment]
Major version with option 1 please, otherwise in 2 years someone will wonder why this is so broken. Also serialize/unserialize in two somewhat disconnected places is not a great idea.
