### ISSUE TITLE
FakeQueue is broken in 2.x

### ISSUE THREAD

**Issue by dimaip** [Flowpack/jobqueue-common#34]
This commit fixed FakeQueue in 3.x branch https://github.com/Flowpack/jobqueue-common/commit/68634d2308426a44cdbd952a37a2dfc70f7f44f7
However the FakeQueue is broken in 2.x branch. Should we cherry-pick the fix into 2.x or just prompt the users to upgrade?

**Comment by daniellienert** [comment]
Fixed with #39 39
